#!/usr/bin/python3

import re
import sys

lines = sys.stdin.read().strip().split('\n')
commit_counts = {}

timezoneregexp = r'( [-+]\d{4})'
date_pattern = re.compile(r'^CommitDate:')

for line in lines:
    match = re.search(timezoneregexp, line)
    match2 = date_pattern.match(line)
    if match and match2:
        tzoffset = match.group()
        if tzoffset in commit_counts:
            commit_counts[tzoffset] += 1
        else:
            commit_counts[tzoffset] = 1

sorted_commits = sorted(commit_counts.items(), key=lambda x: int(x[0]))
for key, value in sorted_commits:
    print(f"{key}: {value}")
